---
title: "title"
author: "eu"
abstract: "abstract"
header-includes:
   - \usepackage[brazil]{babel}
   - \usepackage{bm}
   - \usepackage{float}
geometry: left=1.7cm, right=1.7cm, top=3cm, bottom=3cm
output:
  bookdown::pdf_document2:
editor_options:
  chunk_output_type: console
indent: true
---



```{r setup, include=F}

options(digits = 3)  
options(scipen = 999)
ggplot2::theme_set(ggplot2::theme_minimal()) 
knitr::opts_chunk$set(echo=F, message=F, warning=F, fig.pos = 'H', 
                      fig.align = 'center', fig.width = 6, fig.height= 3.4)
scale_fill_discrete = \(...) ggplot2::scale_fill_brewer(... , palette = "Set2") 
library(tidyverse)
source("utils/trab_final_CEP.R")
```


\section{Introdução}
```{r }
# R code 
iris |> 
  mypdf1::pdf1_summary()
  
```
```{r crftable}

iris |>  
mypdf1::pdf1_tbl_freq(Species) |> 
  mypdf1::pdf1_tbl("You can combine this function too!")
    
```
You cross-reference tables like this: Table \@ref(tab:crftable)

```{r crfgraph, fig.cap = "Fig name"}
plot(rnorm(500))
```
\section{Análise Básica}





```{r}

dados <- readxl::read_excel("CEP.xlsx")
dados$total <- dados$REJEITADAS+dados$LIBERADAS
dados <- dados |> 
  filter(CLIENTE == 'PAMPA')

# graifico U

u <- dados$REJEITADAS/dados$total
UM <- mean(u)
me <- 3*sqrt((UM/dados$total))
LSC <- UM + me
LIC <- UM - me

g_controle2(vari = u,lsc = LSC,lic = LIC,lm = UM,laby = "")
```


You cross-reference figures like this: Figure \@ref(fig:crfgraph)

You can use `#` to create a section too, like this:

\section{Conclusão}
# Bibliography



